Making Predictions
The first step is to develop a function that can make predictions.

This will be needed both in the evaluation of candidate coefficient values in stochastic gradient descent and after the model is finalized and we wish to start making predictions on test data or new data.

Below is a function named predict() that predicts an output value for a row given a set of coefficients.

The first coefficient in is always the intercept, also called the bias or b0 as it is standalone and not responsible for a specific input value.

In [3]:
from math import exp
import numpy as np

def logistic_pred(sample, features):
    #First features is always the bias
    y_pred = features[0]
    for i in range(len(row)-1):
        y_pred += features[i + 1] * sample[i]
    return 1.0 / (1.0 + exp(-y_pred))

In [6]:
dataset = np.genfromtxt(r"C:/Users/tiago/Documents/GitHub/PDEEC0049-Machine-Learning-2018-19/Assignments/heightWeightData.txt", delimiter=',')
dataset

array([[  1.   , 170.18 ,  56.7  ],
       [  2.   , 172.72 ,  63.504],
       [  2.   , 170.18 ,  64.411],
       [  2.   , 152.4  ,  49.896],
       [  2.   , 162.56 ,  43.999],
       [  2.   , 154.94 ,  48.081],
       [  1.   , 200.66 ,  95.255],
       [  2.   , 154.94 ,  49.896],
       [  1.   , 180.34 ,  68.04 ],
       [  2.   , 167.64 ,  65.772],
       [  2.   , 152.4  ,  51.256],
       [  1.   , 180.34 ,  79.379],
       [  1.   , 182.88 ,  65.772],
       [  2.   , 139.7  ,  49.896],
       [  2.   , 162.56 ,  50.803],
       [  2.   , 165.1  ,  61.236],
       [  2.   , 165.1  ,  61.236],
       [  2.   , 180.34 ,  63.504],
       [  2.   , 172.72 ,  58.968],
       [  1.   , 180.34 ,  68.947],
       [  2.   , 170.18 ,  57.607],
       [  1.   , 177.8  ,  64.864],
       [  2.   , 172.72 ,  74.844],
       [  1.   , 182.88 ,  72.576],
       [  1.   , 180.34 ,  83.915],
       [  2.   , 165.1  ,  51.71 ],
       [  2.   , 170.18 ,  52.617],
       [  2.   , 167.64 ,  5

In [13]:
features = np.ones((dataset.shape[0], 1))
features = np.concatenate((features, dataset[:, 1:3]), axis=1)
features

array([[  1.   , 170.18 ,  56.7  ],
       [  1.   , 172.72 ,  63.504],
       [  1.   , 170.18 ,  64.411],
       [  1.   , 152.4  ,  49.896],
       [  1.   , 162.56 ,  43.999],
       [  1.   , 154.94 ,  48.081],
       [  1.   , 200.66 ,  95.255],
       [  1.   , 154.94 ,  49.896],
       [  1.   , 180.34 ,  68.04 ],
       [  1.   , 167.64 ,  65.772],
       [  1.   , 152.4  ,  51.256],
       [  1.   , 180.34 ,  79.379],
       [  1.   , 182.88 ,  65.772],
       [  1.   , 139.7  ,  49.896],
       [  1.   , 162.56 ,  50.803],
       [  1.   , 165.1  ,  61.236],
       [  1.   , 165.1  ,  61.236],
       [  1.   , 180.34 ,  63.504],
       [  1.   , 172.72 ,  58.968],
       [  1.   , 180.34 ,  68.947],
       [  1.   , 170.18 ,  57.607],
       [  1.   , 177.8  ,  64.864],
       [  1.   , 172.72 ,  74.844],
       [  1.   , 182.88 ,  72.576],
       [  1.   , 180.34 ,  83.915],
       [  1.   , 165.1  ,  51.71 ],
       [  1.   , 170.18 ,  52.617],
       [  1.   , 167.64 ,  5

In [35]:
import numpy as np

def logRegF(XX, yy):
    NN, DD = np.shape(XX)
    xdata = np.concatenate((np.ones((NN, 1)), XX), axis=1)
    ww = np.zeros((DD+1, 1))
    for i in range(1000):
        mu = 1 / (1+ np.exp(-np.dot(xdata, ww)))
        temp = np.multiply(mu, (1,mu))
        S = np.diag(temp[:, 0])
        aux = np.linalg.inv(np.dot(np.dot(xdata.T, S), xdata))
        aux = np.dot(np.dot(aux, xdata.T), yy-mu)
        ww += aux
    return ww

In [36]:
labels = dataset[:, 0]-1
labels

array([0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 0.])

In [37]:
logRegF(features, labels)

ValueError: setting an array element with a sequence.